### ISSUE TITLE
Sharing on Facebook doesn't work anymore

### ISSUE THREAD

**Issue by martonlente** [sonnyt/prettySocial#13]
Hello,

Sharing on Facebook using the plugin doesn't work anymore. When clicking a button with `data-type="facebook"`, the following error message appears in Facebook's popup sharing window: *Sorry, something went wrong. We're working on getting this fixed as soon as we can.*. I've tested this behaviour in many browsers, and even on prettySocial's own demo page, and the error consistently happens in all cases.

Do you have an idea for a fix? The plugin otherwise is awesome, it'd be so good to get this sorted out!

Thank you in advance,
Márton Lente

**Comment by haleyngonadi** [comment]
Happening to me as well!

**Comment by jovanzers** [comment]
any solution for this?

**Comment by martonlente** [comment]
Update: After testing prettySocial on multiple websites, sharing on Facebook seems working again! 👍
